import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/61if22pWHbL._AC_SY879_.jpg",
    title: "Apple Iphone 12",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+25 reviews)",
    prevPrice: "$600.00",
    newPrice: "499.99",
    company: "Apple",
    color: "128Gb",
    category: "apple",
  },
  {
    img: "https://m.media-amazon.com/images/I/61i1PIoHtkL._AC_SL1498_.jpg",
    title: "Samsung Galaxy S23",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+50 reviews)",
    prevPrice: "$500,00",
    newPrice: "399.99",
    company: "Samsung",
    color: "128Gb",
    category: "samsung",
  },

  {
    img: "https://m.media-amazon.com/images/I/51wgPOBEbjL._AC_SX679_.jpg",
    title: "Xiaomi 12 Lite",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+99 reviews)",
    prevPrice: "$350.00",
    newPrice: "299.99",
    company: "Xiaomi",
    color: "128Gb",
    category: "xiaomi",
  },
  {
    img: "https://m.media-amazon.com/images/I/71TrxGfNn-L._AC_SL1500_.jpg",
    title: "Huawei P60 Pro 64gb",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+35 reviews)",
    prevPrice: "$550.00",
    newPrice: "499.99",
    company: "Huawei",
    color: "128Gb",
    category: "huawei",
  },
  {
    img: "https://m.media-amazon.com/images/I/61XM1qbUPUL._AC_SX679_.jpg",
    title: "Huawei P30 Dual",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+75 reviews)",
    prevPrice: "$350.00",
    newPrice: "299.99",
    company: "Huawei",
    color: "256Gb",
    category: "huawei",
  },
  {
    img: "https://m.media-amazon.com/images/I/616uMtIWiiL._AC_SX679_.jpg",
    title: "OnePlus Nord N30",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+15 reviews)",
    prevPrice: "$350.00",
    newPrice: "299.99",
    company: "OnePlus",
    color: "256Gb",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/61oQtjPpM-L._AC_SL1500_.jpg",
    title: "Google Pixel 6",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+25 reviews)",
    prevPrice: "$700,00",
    newPrice: "600",
    company: "Google",
    color: "256Gb",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/613O43y5UsL._AC_SL1500_.jpg",
    title: "Motorola Moto G",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+45 reviews)",
    prevPrice: "$350.000",
    newPrice: "299.99",
    company: "Motorola",
    color: "256Gb",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/71Id9mpENBL._AC_SL1500_.jpg",
    title: "Apple iPhone 13",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+15 reviews)",
    prevPrice: "$750.00",
    newPrice: "600",
    company: "Apple",
    color: "256Gb",
    category: "apple",
  },

  {
    img: "https://m.media-amazon.com/images/I/81AT+Flc+EL._AC_SL1500_.jpg",
    title: "Samsung Note 20",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+65 reviews)",
    prevPrice: "$600.00",
    newPrice: "499.99",
    company: "Samsung",
    color: "256Gb",
    category: "samsung",
  },
  {
    img: "https://m.media-amazon.com/images/I/61MgwGYt3ES._AC_SX679_.jpg",
    title: "SAMSUNG Note 9",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+35 reviews)",
    prevPrice: "$350.00",
    newPrice: "299.99",
    company: "Samsung",
    color: "256Gb",
    category: "samsung",
  },
  {
    img: "https://m.media-amazon.com/images/I/71KLR43kq+L._AC_SL1500_.jpg",
    title: "Samsung Note 10",
    star: <AiFillStar className="rating-star" />,
    reviews: "(+45 reviews)",
    prevPrice: "$500.00",
    newPrice: "399.99",
    company: "Samsung",
    color: "256Gb",
    category: "samsung",
  },
  
];

export default data;